openapi: 3.1.0
x-stoplight:
  id: kys2qn99ti7of
info:
  title: Unofficial Swiggy Orders API
  version: '1.0'
  summary: 'Swiggy OpenAPI Specification for the Orders API, used for Order and Restaurant Data'
  contact:
    name: Nemo
    url: 'https://captnemo.in/contact/'
    email: swiggy.openapi@captnemo.in
  description: |
    Welcome to the unofficial Swiggy API OpenAPI Specification.
    Please make sure you check all the APIs:
    1. [Profile](#/reference/profile.yaml)
    2. [Application](#/reference/app.yaml)
    2. [Orders](#/reference/disc.yaml)
    2. [Instamart](#/reference/instamart.yaml)

    There is a guide available at [docs/How-to-get-your-Order-Data-from-Swiggy.html] as well.
servers:
  - url: 'https://disc.swiggy.in/api/v1'
paths:
  /account/orders:
    get:
      summary: Get Swiggy Orders List
      tags: []
      responses:
        '200':
          description: 'This is a Protobuf Response, please see [`swiggy.proto`](swiggy.protobuf) protobuf schema to parse the same.'
          content:
            application/x-protobuf:
              schema:
                type: object
      operationId: get-account-orders
      parameters:
        - schema:
            type: number
            maximum: 5
            minimum: 1
          in: query
          name: order_count
          description: Number of Orders to return
          required: true
        - schema:
            type: string
          in: query
          name: order_id
          description: Used for pagination. Starts Orders from this.
          required: true
        - schema:
            type: number
            default: '0'
            example: '0'
          in: header
          name: latitude
          required: true
        - schema:
            type: number
            default: 0
            example: 0
          in: header
          name: longitude
          required: true
      description: Gets a list of account orders.
      security:
        - tid: []
        - token: []
components:
  schemas: {}
  securitySchemes:
    tid:
      name: tid
      type: apiKey
      in: header
      description: |
        Transaction ID perhaps
    token:
      name: token
      type: apiKey
      in: header
      description: API Token
